// <auto-generated />
using System;
using AleCell.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AleCell.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AleCell.API.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cor")
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<string>("Foto")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cor = "rgba(100,100,100,1)",
                            Foto = "/img/categorias/apple.png",
                            Nome = "Apple"
                        },
                        new
                        {
                            Id = 2,
                            Cor = "rgba(255,100,0,1)",
                            Foto = "/img/categorias/xiaomi.png",
                            Nome = "Xiaomi"
                        },
                        new
                        {
                            Id = 3,
                            Cor = "rgba(0,180,255,1)",
                            Foto = "/img/categorias/acessorios.png",
                            Nome = "Acessórios"
                        });
                });

            modelBuilder.Entity("AleCell.API.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(3000)
                        .HasColumnType("varchar(3000)");

                    b.Property<bool>("Destaque")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Foto")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Qtde")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorCusto")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ValorVenda")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Descricao = "Equipado com o chip A15 Bionic, tela Super Retina XDR de 6,1 polegadas e sistema de câmera dupla de 12 MP com modo Cinema.",
                            Destaque = false,
                            Foto = "/img/produtos/iphone13.png",
                            Nome = "iPhone 13",
                            Qtde = 10,
                            ValorCusto = 2800m,
                            ValorVenda = 3499m
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            Descricao = "Chip A15 Bionic, tela Super Retina XDR com ProMotion (120Hz) e sistema de câmera Pro de 12 MP (Teleobjetiva, Wide e Ultrawide).",
                            Destaque = false,
                            Foto = "/img/produtos/iphone13pro.png",
                            Nome = "iPhone 13 Pro",
                            Qtde = 5,
                            ValorCusto = 3500m,
                            ValorVenda = 4299m
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 1,
                            Descricao = "A maior tela da linha 13 com 6,7 polegadas, bateria de longa duração, chip A15 Bionic e câmeras Pro de alto desempenho.",
                            Destaque = false,
                            Foto = "/img/produtos/iphone13promax.png",
                            Nome = "iPhone 13 Pro Max",
                            Qtde = 5,
                            ValorCusto = 4000m,
                            ValorVenda = 4899m
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 1,
                            Descricao = "iPhone 14 com chip A15 Bionic, câmera dupla avançada e detecção de acidente. Bateria de longa duração.",
                            Destaque = false,
                            Foto = "/img/produtos/iphone14.png",
                            Nome = "iPhone 14",
                            Qtde = 8,
                            ValorCusto = 2800m,
                            ValorVenda = 3999m
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 1,
                            Descricao = "Introduz a Dynamic Island, chip A16 Bionic, tela Sempre Ativa e câmera principal de 48 MP para detalhes incríveis.",
                            Destaque = false,
                            Foto = "/img/produtos/iphone14pro.png",
                            Nome = "iPhone 14 Pro",
                            Qtde = 4,
                            ValorCusto = 4500m,
                            ValorVenda = 5499m
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 1,
                            Descricao = "Tela de 6,7 polegadas com Dynamic Island, chip A16 Bionic, câmera de 48 MP e a melhor autonomia de bateria da linha 14.",
                            Destaque = false,
                            Foto = "/img/produtos/iphone14promax.png",
                            Nome = "iPhone 14 Pro Max",
                            Qtde = 3,
                            ValorCusto = 5000m,
                            ValorVenda = 6199m
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 1,
                            Descricao = "iPhone 15 com chip A16 Bionic, câmera principal de 48MP e porta USB-C. Design em alumínio resistente com vidro Ceramic Shield.",
                            Destaque = true,
                            Foto = "/img/produtos/iphone15.png",
                            Nome = "iPhone 15",
                            Qtde = 8,
                            ValorCusto = 3500m,
                            ValorVenda = 4999m
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 1,
                            Descricao = "Estrutura em titânio aeroespacial, chip A17 Pro, botão de Ação personalizável e sistema de câmera Pro avançado.",
                            Destaque = false,
                            Foto = "/img/produtos/iphone15pro.png",
                            Nome = "iPhone 15 Pro",
                            Qtde = 6,
                            ValorCusto = 5500m,
                            ValorVenda = 6799m
                        },
                        new
                        {
                            Id = 9,
                            CategoriaId = 1,
                            Descricao = "O iPhone mais avançado da Apple. Chip A17 Pro, câmera de 48MP com zoom óptico 5x, tela Super Retina XDR de 6.7 polegadas e titânio grau aeroespacial.",
                            Destaque = true,
                            Foto = "/img/produtos/iphone15promax.png",
                            Nome = "iPhone 15 Pro Max",
                            Qtde = 5,
                            ValorCusto = 7000m,
                            ValorVenda = 8999m
                        },
                        new
                        {
                            Id = 10,
                            CategoriaId = 1,
                            Descricao = "Novo Controle da Câmera, chip A18 ultraeficiente, fotos espaciais para Apple Vision Pro e cores vibrantes.",
                            Destaque = true,
                            Foto = "/img/produtos/iphone16.png",
                            Nome = "iPhone 16",
                            Qtde = 10,
                            ValorCusto = 5200m,
                            ValorVenda = 6499m
                        },
                        new
                        {
                            Id = 11,
                            CategoriaId = 1,
                            Descricao = "Tela maior de 6,3 polegadas, chip A18 Pro, gravação de vídeo 4K Dolby Vision a 120 qps e estrutura em titânio.",
                            Destaque = true,
                            Foto = "/img/produtos/iphone16pro.png",
                            Nome = "iPhone 16 Pro",
                            Qtde = 5,
                            ValorCusto = 6800m,
                            ValorVenda = 8299m
                        },
                        new
                        {
                            Id = 12,
                            CategoriaId = 1,
                            Descricao = "A maior tela de iPhone já feita (6,9 polegadas), chip A18 Pro, Controle da Câmera e bateria de altíssima duração.",
                            Destaque = true,
                            Foto = "/img/produtos/iphone16promax.png",
                            Nome = "iPhone 16 Pro Max",
                            Qtde = 5,
                            ValorCusto = 7800m,
                            ValorVenda = 9499m
                        },
                        new
                        {
                            Id = 13,
                            CategoriaId = 1,
                            Descricao = "Rumores indicam tela de 120Hz em toda a linha, chip A19 e design ultrafino. (Modelo em pré-lançamento/estimado).",
                            Destaque = false,
                            Foto = "/img/produtos/iphone17.png",
                            Nome = "iPhone 17",
                            Qtde = 2,
                            ValorCusto = 6000m,
                            ValorVenda = 7299m
                        },
                        new
                        {
                            Id = 14,
                            CategoriaId = 1,
                            Descricao = "Expectativa de 12GB de RAM, chip A19 Pro e câmeras de 48MP em todos os sensores. (Modelo em pré-lançamento/estimado).",
                            Destaque = false,
                            Foto = "/img/produtos/iphone17pro.png",
                            Nome = "iPhone 17 Pro",
                            Qtde = 2,
                            ValorCusto = 7500m,
                            ValorVenda = 8999m
                        },
                        new
                        {
                            Id = 15,
                            CategoriaId = 1,
                            Descricao = "O topo de linha absoluto com Face ID sob a tela e zoom óptico aprimorado. (Modelo em pré-lançamento/estimado).",
                            Destaque = false,
                            Foto = "/img/produtos/iphone17promax.png",
                            Nome = "iPhone 17 Pro Max",
                            Qtde = 2,
                            ValorCusto = 8500m,
                            ValorVenda = 10499m
                        },
                        new
                        {
                            Id = 16,
                            CategoriaId = 2,
                            Descricao = "Flagship da Xiaomi com câmeras Leica, Snapdragon 8 Gen 3, tela AMOLED 120Hz e carregamento ultra-rápido de 90W.",
                            Destaque = true,
                            Foto = "/img/produtos/xiaomi14ultra.png",
                            Nome = "Xiaomi 14 Ultra",
                            Qtde = 3,
                            ValorCusto = 4500m,
                            ValorVenda = 5999m
                        },
                        new
                        {
                            Id = 17,
                            CategoriaId = 2,
                            Descricao = "Melhor custo-benefício com câmera de 200MP, tela AMOLED 120Hz e bateria de 5100mAh. Carregamento rápido 67W.",
                            Destaque = true,
                            Foto = "/img/produtos/redminote13pro.png",
                            Nome = "Xiaomi Redmi Note 13 Pro",
                            Qtde = 12,
                            ValorCusto = 1200m,
                            ValorVenda = 1899m
                        },
                        new
                        {
                            Id = 18,
                            CategoriaId = 3,
                            Descricao = "Capa oficial Apple com suporte MagSafe, proteção premium e acabamento em silicone.",
                            Destaque = false,
                            Foto = "/img/produtos/capa-iphone-magsafe.png",
                            Nome = "Capa iPhone 15 Pro Max - MagSafe",
                            Qtde = 20,
                            ValorCusto = 150m,
                            ValorVenda = 299m
                        });
                });

            modelBuilder.Entity("AleCell.API.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Foto")
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "baab58a9-a217-4fb3-b436-4952deef16cd",
                            DataNascimento = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@alecell.com.br",
                            EmailConfirmed = true,
                            Foto = "/img/usuarios/avatar.png",
                            LockoutEnabled = true,
                            Nome = "Administrador AleCell",
                            NormalizedEmail = "ADMIN@ALECELL.COM.BR",
                            NormalizedUserName = "ADMIN@ALECELL.COM.BR",
                            PasswordHash = "AQAAAAIAAYagAAAAEKwcoBkkV/vHq4ePD6BHWDlsIgbaWjRywdwFisZRJwknpRZAFJQqN/Wv/6VFw4zQ8Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f9f634ec-b9da-4557-89b8-d6be952a8c98",
                            TwoFactorEnabled = false,
                            UserName = "admin@alecell.com.br"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0b44ca04-f6b0-4a8f-a953-1f2330d30894",
                            ConcurrencyStamp = "d510f6a7-6806-428c-b0c5-8816bd918a14",
                            Name = "Administrador",
                            NormalizedName = "ADMINISTRADOR"
                        },
                        new
                        {
                            Id = "ddf093a6-6cb5-4ff7-9a64-83da34aee005",
                            ConcurrencyStamp = "e3493ca8-bd85-4805-9151-9088f7f49cd9",
                            Name = "Cliente",
                            NormalizedName = "CLIENTE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            RoleId = "0b44ca04-f6b0-4a8f-a953-1f2330d30894"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AleCell.API.Models.Produto", b =>
                {
                    b.HasOne("AleCell.API.Models.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AleCell.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AleCell.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AleCell.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AleCell.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AleCell.API.Models.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
